SELECT BOARD_ID, WRITER_ID, TITLE, PRICE, (
CASE
    WHEN STATUS = 'DONE' THEN '거래완료'
    when status = 'SALE' THEN '판매중'
    else '예약중'
end
) as STATUS
FROM USED_GOODS_BOARD
WHERE CREATED_DATE = '2022-10-05'
ORDER BY BOARD_ID DESC